config/routes.rb
Rails.application.routes.draw do
  resources :todos
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    
  def index
    @todos = Todo.all
  end
  
  def new
    @todo = Todo.new
  end
  
  def create
    @todo = Todo.create(todo_params)
    redirect_to todos_path
  end
  
  def edit
    @todo = Todo.find(params[:id])
  end
  
  def update
    @todo = Todo.find(params[:id]) 
    @todo.update(todo_params)
    redirect_to todos_path
  end
  
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  private
  def todo_params
    params.require(:todo).permit(:item)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/edit.html.slim
h2 Edit todo

= form_for(@todo) do |f|
  = f.text_field :item
  = f.submit
end

app/views/todos/index.html.slim
- @todos.each do |todo|
  ul
    li = todo.item
    p 
      = link_to "Edit", edit_todo_path(todo)
	  p
	    = link_to "Delete", todo_path(todo), method: :delete
= link_to("New", new_todo_path)

app/views/todos/new.html.slim
= form_for(@todo) do |f|
  p
    = f.text_field :item, :placeholder => "Add new item"
  p
    = f.submit
end